data:
    name: 'finger'
    cache_in_memory: false
    validation_size: 100
model:
    name: 'super_point'
    batch_size: 50
    learning_rate: 0.001
    detection_threshold: 0.07 #0.0001 #0.015  # 0.001
    nms: 14
    #top_k: 300
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.85
eval_iter: -1
