data:
    name: 'finger'
    cache_in_memory: false
    validation_size: 96
    labels: outputs/magic-point_finger-export1  # use your own labels here
    augmentation:
        photometric:
            enable: true
            primitives: [
                'additive_speckle_noise',
                'additive_gaussian_noise', 'motion_blur']
            params:
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                motion_blur: {max_kernel_size: 5}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: false
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 0.5
            allow_artifacts: true
        valid_border_margin: 3
model:
    name: 'super_point'
    batch_size: 8
    eval_batch_size: 8
    learning_rate: 0.0001
    lambda_d: 300
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 1
    detection_threshold: 0.001
    nms: 4
    top_k: 300
train_iter: 30000
validation_interval: 100
